### ISSUE TITLE
Please help!!!

### ISSUE THREAD

**Issue by hieuduy98** [nhatnor123/do_an_tot_nghiep#1]
Can you add readme.md? I really need this. Ur project has huge potential and this can replace Microsoft's Teams.

**Comment by nhatnor123** [comment]
u can folow this guide. but it's language is Vietnamese :))
[README.md](https://github.com/nhatnor123/do_an_tot_nghiep/files/6775462/README.md)

**Comment by nhatnor123** [comment]
btw, thanks for your encouragement

**Comment by hieuduy98** [comment]
Super nice, and please add english in your doc. Thank you.

**Comment by nhatnor123** [comment]
Done

**Comment by sonnb270898** [comment]
omg !!!!! tks internet for recommending me to this repo. 
This repo should be the super ultra best top 1 BK
